import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";

import { Figtree } from "next/font/google";
import Footer from "@/components/shared/footer";
import Providers from "@/components/shared/providers";

const figtree = Figtree({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "MediPro Demo Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-background ${figtree.className} antialiased`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
