import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";

import { Figtree } from "next/font/google";
import Footer from "@/components/shared/footer";

const figtree = Figtree({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-background ${figtree.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
